# Site settings
title: Richard Perry
author: Richard Perry
email: notes@perry-online.me.uk
description: > 
  This is my own personal site for keeping a basic journal and some notes for my Chinese Language
  Learning. Hopefully, once my Chinese improved, I will also start writing some journal entries in
  Mandarin. The site is not for general consumption, but I like Jekyll   & GitHub so I am using the
  combination for my own benefit.
baseurl: ""
url: "http://zh.perry-online.me.uk"
twitter_username: richard_p2_ZH
github_username:  richardp2

# Build settings
markdown: kramdown
permalink: /:categories/:title/
paginate: 20
paginate_path: "page/:num"
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

languages: &languages
  - name: 'English'
    value: 'en'
  - name: '中文'
    value: 'zh'

# Define defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: richard
  -
    scope:
      path: pages
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: en/_posts
    values:
      lang: en-gb
  -
    scope:
      path: zh/_posts
    values:
      lang: zh-cn
      
prose:
  rooturl: ''
  siteurl: 'http://zh.perry-online.me.uk/'
  relativeLinks: 'http://zh.perry-online.me.uk/links.jsonp'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    en/_posts:
      - name: "date"
        field:
          element: "text"
          label: "Date (YYYY-MM-DD HH:MM:SS)"
          value: "2014-11-01 22:30:00+00:00"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "author"
        field:
          element: "hidden"
          value: "richard"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true