# Site settings
title: Richard Perry
author: Richard Perry
email: notes@perry-online.me.uk
description: > # this means to ignore newlines until "baseurl:"
  This is my own personal site for keeping notes and maybe even a journal of my
  Chinese Language learning. It is not for general consumption, but I like Jekyll
  & GitHub so I am using the combination for my own benefit
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zh.perry-online.me.uk" # the base hostname & protocol for your site
twitter_username: richard_p2_ZH
github_username:  richardp2

# Build settings
markdown: kramdown
permalink: pretty
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Define defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      
prose:
  rooturl: '_posts'
  siteurl: 'http://zh.perry-online.me.uk/'
  media: 'images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date (YYYY-MM-DD HH:MM:SS)"
          value: "2014-06-08 10:30:00"